services:
  monolith:
    image: ${MONOLITH_IMAGE:-${IMAGE_REPO:-ghcr.io/rindrics/yoshimoto-samonji/monolith}:latest}
    ports:
      - "${PLUMBER_PORT}:${CONTAINER_PORT:-8000}"
    environment:
      PLUMBER_PORT: "${CONTAINER_PORT:-8000}"
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
    volumes:
      - ./adapters/legacy/R:/app/R
      - ./schema:/app/../../schema
    networks:
      - yoshimoto-samonji

networks:
  yoshimoto-samonji:
    driver: bridge
